# Generated by Django 2.2.4 on 2020-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='completeAddress',
        ),
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
