# Generated by Django 2.2.4 on 2020-08-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverPhoto1', models.ImageField(blank=True, null=True, upload_to='')),
                ('coverPhoto2', models.ImageField(blank=True, null=True, upload_to='')),
                ('shippingMessage', models.TextField(max_length=250)),
                ('offerMessage', models.TextField(max_length=250)),
                ('maintanance', models.BooleanField(default=False)),
            ],
        ),
    ]
