# Generated by Django 2.2.4 on 2020-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200802_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='coverPhoto1',
            field=models.ImageField(blank=True, null=True, upload_to='app_info'),
        ),
    ]
