# Generated by Django 2.2.4 on 2020-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200807_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='exicutive_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='offer_message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='shipping_message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
