# Generated by Django 2.2.4 on 2020-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200808_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='offer_message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='shipping_message',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
