# Generated by Django 2.2.4 on 2020-08-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200808_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shipping_contract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
