# Generated by Django 2.2.4 on 2020-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shop_shipping_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
