# Generated by Django 2.2.4 on 2020-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200817_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='/media/place/default_place.jpg', null=True, upload_to='place'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='/media/shop/default_shop.jpg', null=True, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_1',
            field=models.ImageField(blank=True, default='/media/shop/default_shop.jpg', null=True, upload_to='shop'),
        ),
    ]
