# Generated by Django 2.2.4 on 2020-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200821_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='item_quantity',
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, default='/place/default_place.jpg', null=True, upload_to='place'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, default='/shop/default_shop.jpg', null=True, upload_to='shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image_1',
            field=models.ImageField(blank=True, default='/shop/default_shop.jpg', null=True, upload_to='shop'),
        ),
    ]
