# Generated by Django 2.2.4 on 2020-08-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200823_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeofpayment',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='paymentMode',
            field=models.ManyToManyField(blank=True, null=True, to='core.ModeOfPayment'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='paymentMode',
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ModeOfPayment'),
        ),
    ]
