# Generated by Django 2.2.4 on 2020-08-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200823_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='can_update_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
