# Generated by Django 2.2.4 on 2020-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_orderstatus_can_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_for_place_only',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_for_shop_only',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_universal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='places',
            field=models.ManyToManyField(to='core.Place'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='shops',
            field=models.ManyToManyField(to='core.Shop'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
