# Generated by Django 2.2.4 on 2020-08-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200828_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
