# Generated by Django 2.2.4 on 2020-08-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_coupon_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='offer',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
