# Generated by Django 2.2.4 on 2020-08-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_coupon_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_only_once_per_user',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
