# Generated by Django 2.2.4 on 2020-09-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coupon_is_only_once_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_variations',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_variation',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Variation'),
        ),
        migrations.AddField(
            model_name='variation',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ItemVariation',
        ),
    ]
