# Generated by Django 2.2.4 on 2020-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='villages',
        ),
        migrations.RemoveField(
            model_name='district',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='place',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='state',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='village',
            name='places',
        ),
        migrations.AddField(
            model_name='shop',
            name='cluster_shop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='locality_shop',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_areas',
            field=models.ManyToManyField(related_name='ShopServiceAreas', to='core.Area'),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_localities',
            field=models.ManyToManyField(related_name='ShopServicePlaces', to='core.Place'),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_villages',
            field=models.ManyToManyField(related_name='ShopServiceVillages', to='core.Village'),
        ),
        migrations.AddField(
            model_name='shop',
            name='village_shop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='paymentMode',
            field=models.ManyToManyField(to='core.ModeOfPayment'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='product_categories',
            field=models.ManyToManyField(to='core.ProductCategory'),
        ),
    ]
