# Generated by Django 2.2.4 on 2020-09-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200909_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='item_stock',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='stock_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
