# Generated by Django 2.2.4 on 2020-09-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200920_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock_weight',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
