# Generated by Django 2.2.4 on 2020-09-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200923_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_count',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock_count',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
