# Generated by Django 2.2.4 on 2020-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_place_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Malayalam', 'Malayalam')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, default='/product/no_image.png', null=True, upload_to='product'),
        ),
    ]
