# Generated by Django 2.2.4 on 2020-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20201006_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
