# Generated by Django 2.2.4 on 2020-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201006_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default='English', max_length=20, null=True),
        ),
    ]
